import { NextPage } from "next";
import Head from "next/head";
import {
  Box,
  Container,
  Divider,
  Heading,
  Text,
  useColorModeValue,
  VStack,
  Wrap,
} from "@chakra-ui/react";
import Image from "components/image";
import { staticPath } from "../libs/$path";

const Home: NextPage = () => {
  const grayColor = useColorModeValue("gray.500", "gray.400");

  return (
    <Container maxW="3xl" pt="8" pb="12">
      <Head>
        <title>subaru links</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrap spacing="6" my="8" as="div" align="center">
        <Box w="20" h="20" borderRadius="full" overflow="hidden">
          <Image
            webp={staticPath.avatar_webp}
            jpg={staticPath.avatar_jpg}
            alt="avatar"
            w="512"
            h="512"
          />
        </Box>
        <VStack spacing="2" align="left">
          <Heading as="h1" size="xl">
            subaru links
          </Heading>
          <Text fontSize="sm" color={grayColor}>
            Links to portfolios, SNS accounts, and other sites related to
            subaru.
          </Text>
        </VStack>
      </Wrap>
      <Divider />
    </Container>
  );
};

export default Home;
